=begin
#Staffology Payroll API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1
Contact: duane@staffology.co.uk
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.29
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::TagApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TagApi' do
  before do
    # run before each test
    @instance = SwaggerClient::TagApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TagApi' do
    it 'should create an instance of TagApi' do
      expect(@instance).to be_instance_of(SwaggerClient::TagApi)
    end
  end

  # unit tests for create_tag
  # Create Tag
  # Creates a new Tag for the Employer.
  # @param employer_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Tag] :body 
  # @return [Tag]
  describe 'create_tag test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_tag
  # Delete Tag
  # Deletes the specified Tag.
  # @param employer_id 
  # @param code 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_tag test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_tag
  # Get Tag
  # Gets the Tag specified.
  # @param employer_id The Id of the Employer to which the Tag belongs.
  # @param code 
  # @param [Hash] opts the optional parameters
  # @return [Tag]
  describe 'get_tag test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for index_tag
  # List Tags
  # Lists all Tags for an Employer.
  # @param employer_id The Id of the Employer for which you want to list Tags
  # @param [Hash] opts the optional parameters
  # @return [Array<Item>]
  describe 'index_tag test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_tag
  # Update Tag
  # Updates a Tag for the Employer.
  # @param employer_id 
  # @param code 
  # @param [Hash] opts the optional parameters
  # @option opts [Tag] :body 
  # @return [Tag]
  describe 'update_tag test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
