=begin
#Staffology Payroll API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1
Contact: duane@staffology.co.uk
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.29
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::FpsEmployeeTaxCode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FpsEmployeeTaxCode' do
  before do
    # run before each test
    @instance = SwaggerClient::FpsEmployeeTaxCode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FpsEmployeeTaxCode' do
    it 'should create an instance of FpsEmployeeTaxCode' do
      expect(@instance).to be_instance_of(SwaggerClient::FpsEmployeeTaxCode)
    end
  end
  describe 'test attribute "basis_non_cumulative"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "tax_regime"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "tax_code"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
