=begin
#Staffology Payroll API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1
Contact: duane@staffology.co.uk
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.29
=end

require 'date'

module SwaggerClient
  class AuthScheme
    O_AUTH1 = 'OAuth1'.freeze
    O_AUTH2 = 'OAuth2'.freeze
    BASIC = 'Basic'.freeze
    API_KEY_IN_HEADER = 'ApiKeyInHeader'.freeze
    HMAC = 'Hmac'.freeze
    O_AUTH2_CC = 'OAuth2Cc'.freeze
    O_AUTH2_PASSWORD = 'OAuth2Password'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = AuthScheme.constants.select { |c| AuthScheme::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #AuthScheme" if constantValues.empty?
      value
    end
  end
end
