=begin
#Staffology Payroll API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1
Contact: duane@staffology.co.uk
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.29
=end

require 'date'

module SwaggerClient
  class BankPaymentInstructionsCsvFormat
    STANDARD_CSV = 'StandardCsv'.freeze
    TELLEROO = 'Telleroo'.freeze
    BARCLAYS_BACS = 'BarclaysBacs'.freeze
    SANTANDER_BACS = 'SantanderBacs'.freeze
    SIF = 'Sif'.freeze
    REVOLUT = 'Revolut'.freeze
    STANDARD18_FASTER_PAYMENTS = 'Standard18FasterPayments'.freeze
    STANDARD18_BACS = 'Standard18Bacs'.freeze
    BANKLINE = 'Bankline'.freeze
    BANKLINE_BULK = 'BanklineBulk'.freeze
    STANDARD_CSV_BACS = 'StandardCsvBacs'.freeze
    LLOYDS_MULTIPLE_STANDARD_CSV_BACS = 'LloydsMultipleStandardCsvBacs'.freeze
    LLOYDS_V11_CSV_BACS = 'LloydsV11CsvBacs'.freeze
    CO_OP_BULK_CSV_BACS = 'CoOpBulkCsvBacs'.freeze
    CO_OP_FASTER_PAYMENTS_CSV = 'CoOpFasterPaymentsCsv'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = BankPaymentInstructionsCsvFormat.constants.select { |c| BankPaymentInstructionsCsvFormat::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #BankPaymentInstructionsCsvFormat" if constantValues.empty?
      value
    end
  end
end
