=begin
#Staffology Payroll API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1
Contact: duane@staffology.co.uk
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.29
=end

require 'date'

module SwaggerClient
  class BenefitDetailsNonClass1AType
    OTHER = 'Other'.freeze
    MULTIPLE = 'Multiple'.freeze
    LOANS_WRITTEN_OR_WAIVED = 'LoansWrittenOrWaived'.freeze
    NURSERY_PLACES = 'NurseryPlaces'.freeze
    EDUCATIONAL_ASSITANCE = 'EducationalAssitance'.freeze
    SUBSCRIPTIONS_AND_FEES = 'SubscriptionsAndFees'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = BenefitDetailsNonClass1AType.constants.select { |c| BenefitDetailsNonClass1AType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #BenefitDetailsNonClass1AType" if constantValues.empty?
      value
    end
  end
end
