=begin
#Staffology Payroll API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1
Contact: duane@staffology.co.uk
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.29
=end

require 'date'

module SwaggerClient
  class ExternalDataProviderId
    SMART_PENSION_EMPLOYER = 'SmartPension_Employer'.freeze
    SMART_PENSION_ADVISER = 'SmartPension_Adviser'.freeze
    PEOPLES_PENSION = 'PeoplesPension'.freeze
    XERO = 'Xero'.freeze
    QBO = 'Qbo'.freeze
    SAGE = 'Sage'.freeze
    NEST = 'Nest'.freeze
    CASHPLUS = 'Cashplus'.freeze
    BREATHE_HR = 'BreatheHr'.freeze
    KASH_FLOW = 'KashFlow'.freeze
    RECKON = 'Reckon'.freeze
    FREE_AGENT = 'FreeAgent'.freeze
    FREE_AGENT_PM = 'FreeAgentPm'.freeze
    MODULR = 'Modulr'.freeze
    SQUARE = 'Square'.freeze
    CEZANNE = 'Cezanne'.freeze
    CIPHR = 'Ciphr'.freeze
    TELLEROO = 'Telleroo'.freeze
    WE_WORKED = 'WeWorked'.freeze
    ROTA_CLOUD = 'RotaCloud'.freeze
    QUINYX = 'Quinyx'.freeze
    CSOD = 'Csod'.freeze
    PLANDAY = 'Planday'.freeze
    STARLING = 'Starling'.freeze
    DEPUTY = 'Deputy'.freeze
    BOTTOMLINE = 'Bottomline'.freeze
    TWINFIELD = 'Twinfield'.freeze
    MYE_PAY_WINDOW = 'MyePayWindow'.freeze
    I_FINANCE = 'IFinance'.freeze
    ACCOUNTS_IQ = 'AccountsIQ'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ExternalDataProviderId.constants.select { |c| ExternalDataProviderId::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ExternalDataProviderId" if constantValues.empty?
      value
    end
  end
end
