=begin
#Staffology Payroll API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1
Contact: duane@staffology.co.uk
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.29
=end

require 'date'

module SwaggerClient
  class PensionContributionLevelType
    USER_DEFINED = 'UserDefined'.freeze
    STATUTORY_MINIMUM = 'StatutoryMinimum'.freeze
    NHS2015 = 'Nhs2015'.freeze
    TP2020 = 'Tp2020'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = PensionContributionLevelType.constants.select { |c| PensionContributionLevelType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #PensionContributionLevelType" if constantValues.empty?
      value
    end
  end
end
