=begin
#Staffology Payroll API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1
Contact: duane@staffology.co.uk
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.29
=end

require 'date'

module SwaggerClient
  class PensionCsvFormat
    PAPDIS = 'Papdis'.freeze
    NEST = 'Nest'.freeze
    NOW_PENSIONS = 'NowPensions'.freeze
    TEACHERS_PENSION_MDC = 'TeachersPensionMdc'.freeze
    TEACHERS_PENSION_MCR = 'TeachersPensionMcr'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = PensionCsvFormat.constants.select { |c| PensionCsvFormat::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #PensionCsvFormat" if constantValues.empty?
      value
    end
  end
end
